cls2HanyuPinyinPrimes = \
{'E': ['¨º'],
 'R': ['chi', 'ri', 'shi', 'zhi'],
 'Z': ['ci', 'si', 'zi'],
 'a': ['a',
       'ba',
       'ca',
       'cha',
       'da',
       'fa',
       'ga',
       'ha',
       'ka',
       'la',
       'ma',
       'na',
       'pa',
       'sa',
       'sha',
       'ta',
       'za',
       'zha'],
 'ai': ['ai',
        'bai',
        'cai',
        'chai',
        'dai',
        'gai',
        'hai',
        'kai',
        'lai',
        'mai',
        'nai',
        'pai',
        'sai',
        'shai',
        'tai',
        'zai',
        'zhai'],
 'an': ['an',
        'ban',
        'can',
        'chan',
        'dan',
        'fan',
        'gan',
        'han',
        'kan',
        'lan',
        'man',
        'nan',
        'pan',
        'ran',
        'san',
        'shan',
        'tan',
        'zan',
        'zhan'],
 'ang': ['ang',
         'bang',
         'cang',
         'chang',
         'dang',
         'fang',
         'gang',
         'hang',
         'kang',
         'lang',
         'mang',
         'nang',
         'pang',
         'rang',
         'sang',
         'shang',
         'tang',
         'zang',
         'zhang'],
 'ao': ['ao',
        'bao',
        'cao',
        'chao',
        'dao',
        'gao',
        'hao',
        'kao',
        'lao',
        'mao',
        'nao',
        'pao',
        'rao',
        'sao',
        'shao',
        'tao',
        'zao',
        'zhao'],
 'e': ['ce',
       'che',
       'de',
       'e',
       'ge',
       'he',
       'ke',
       'le',
       'me',
       'ne',
       're',
       'se',
       'she',
       'te',
       'ze',
       'zhe'],
 'ei': ['bei',
        'dei',
        'ei',
        'fei',
        'gei',
        'hei',
        'kei',
        'lei',
        'mei',
        'nei',
        'pei',
        'shei',
        'zei',
        'zhei'],
 'en': ['ben',
        'cen',
        'chen',
        'chun',
        'cun',
        'den',
        'dun',
        'en',
        'fen',
        'gen',
        'gun',
        'hen',
        'hun',
        'ken',
        'kun',
        'len',
        'lun',
        'men',
        'nen',
        'nun',
        'pen',
        'ren',
        'run',
        'sen',
        'shen',
        'shun',
        'sun',
        'tun',
        'wen',
        'zen',
        'zhen',
        'zhun',
        'zun'],
 'eng': ['beng',
         'ceng',
         'cheng',
         'deng',
         'eng',
         'feng',
         'geng',
         'heng',
         'keng',
         'leng',
         'meng',
         'neng',
         'peng',
         'reng',
         'seng',
         'sheng',
         'teng',
         'zeng',
         'zheng'],
 'er': ['er'],
 'hng': ['hng'],
 'i': ['bi', 'di', 'ji', 'li', 'mi', 'ni', 'pi', 'qi', 'ti', 'xi', 'yi'],
 'iE': ['bie',
        'die',
        'jie',
        'jue',
        'lie',
        'lve',
        'mie',
        'nie',
        'nve',
        'pie',
        'qie',
        'que',
        'tie',
        'xie',
        'xue',
        'ye',
        'yue'],
 'ia': ['dia', 'jia', 'lia', 'nia', 'qia', 'xia', 'ya'],
 'ian': ['bian',
         'dian',
         'jian',
         'lian',
         'mian',
         'nian',
         'pian',
         'qian',
         'tian',
         'xian',
         'yan'],
 'iang': ['jiang', 'liang', 'niang', 'qiang', 'xiang', 'yang'],
 'iao': ['biao',
         'diao',
         'jiao',
         'liao',
         'miao',
         'niao',
         'piao',
         'qiao',
         'tiao',
         'xiao',
         'yao'],
 'in': ['bin',
        'din',
        'jin',
        'jun',
        'lin',
        'min',
        'nin',
        'pin',
        'qin',
        'qun',
        'xin',
        'xun',
        'yin',
        'yun'],
 'ing': ['bing',
         'ding',
         'jing',
         'ling',
         'ming',
         'ning',
         'ping',
         'qing',
         'ting',
         'xing',
         'ying'],
 'io': ['yo'],
 'iong': ['jiong', 'qiong', 'xiong', 'yong'],
 'iou': ['diu', 'jiu', 'liu', 'miu', 'niu', 'qiu', 'xiu', 'you'],
 'm': ['m'],
 'n': ['n'],
 'ng': ['ng'],
 'o': ['bo', 'fo', 'lo', 'mo', 'o', 'po'],
 'ong': ['chong',
         'cong',
         'dong',
         'gong',
         'hong',
         'kong',
         'long',
         'nong',
         'rong',
         'song',
         'tong',
         'zhong',
         'zong'],
 'ou': ['chou',
        'cou',
        'dou',
        'fou',
        'gou',
        'hou',
        'kou',
        'lou',
        'mou',
        'nou',
        'ou',
        'pou',
        'rou',
        'shou',
        'sou',
        'tou',
        'zhou',
        'zou'],
 'u': ['bu',
       'chu',
       'cu',
       'du',
       'fu',
       'gu',
       'hu',
       'ku',
       'lu',
       'mu',
       'nu',
       'pu',
       'ru',
       'shu',
       'su',
       'tu',
       'wu',
       'zhu',
       'zu'],
 'ua': ['chua', 'gua', 'hua', 'kua', 'rua', 'shua', 'wa', 'zhua'],
 'uai': ['chuai', 'guai', 'huai', 'kuai', 'shuai', 'wai', 'zhuai'],
 'uan': ['chuan',
         'cuan',
         'duan',
         'guan',
         'huan',
         'kuan',
         'luan',
         'nuan',
         'ruan',
         'shuan',
         'suan',
         'tuan',
         'wan',
         'zhuan',
         'zuan'],
 'uang': ['chuang', 'guang', 'huang', 'kuang', 'shuang', 'wang', 'zhuang'],
 'uei': ['chui',
         'cui',
         'dui',
         'gui',
         'hui',
         'kui',
         'rui',
         'shui',
         'sui',
         'tui',
         'wei',
         'zhui',
         'zui'],
 'ueng': ['weng'],
 'uo': ['chuo',
        'cuo',
        'duo',
        'guo',
        'huo',
        'kuo',
        'luo',
        'nuo',
        'ruo',
        'shuo',
        'suo',
        'tuo',
        'wo',
        'zhuo',
        'zuo'],
 'uong': ['wong'],
 'v': ['ju', 'lv', 'nv', 'qu', 'xu', 'yu'],
 'van': ['juan', 'quan', 'xuan', 'yuan']}
