grammar_XOAs = '''
Inline_Path_OP_Items1 Inline_Path_OP_Items0 Inline_Path_OP_Item
Inline_ListItem_OPs1 Inline_ListItem_OPs0 Inline_ListItem_OP
Inline_DictItem_OPs1 Inline_DictItem_OPs0 Inline_DictItem_OP
CharStringBodyLine_Nulls1 CharStringBodyLine_Nulls0 CharStringBodyLine_Null
ListBodyItem_Nulls1 ListBodyItem_Nulls0 ListBodyItem_Null
DictBodyItem_Nulls1 DictBodyItem_Nulls0 DictBodyItem_Null
'''
