
from ..CJK_pinyin__ucd.normal_pinyin_prime2full_pinyin_prime_ym_cls_ex_pair import \
    normal_pinyin_prime2full_pinyin_prime_ym_cls_ex_pair
from ..CJK_pinyin__ucd.normal_pinyin_prime2full_pinyin_prime_ym_cls_ex_pair____ucdXcedict import \
    normal_pinyin_prime2full_pinyin_prime_ym_cls_ex_pair____ucdXcedict

