
TINY_CASE = 'TINY_CASE'
SMALL_CASE = 'SMALL_CASE'
LARGE_CASE = 'LARGE_CASE'
HUGE_CASE = 'HUGE_CASE'
RESERVED_CASE = 'RESERVED_CASE'
USER_CASE = 'USER_CASE'

HUGE_OR_RESERVED_CASE = 'HUGE_OR_RESERVED_CASE'

cases_TSLH = (TINY_CASE, SMALL_CASE, LARGE_CASE, HUGE_CASE)
