r'''[[[
e ../../python3_src/nn_ns/math_nn/numbers/exponents4Fermat_prime.py
py -m nn_ns.math_nn.numbers.exponents4Fermat_prime

Fermat_prime |<| Fermat_number
Fermat_number
  https://oeis.org/A000215
    It is conjectured that just the first 5 numbers in this sequence are primes.


拓展__all__:
    view ../../python3_src/nn_ns/math_nn/numbers/Mersenne_exponents.py

[[
What is Digital root? If we add up the digits of a number until there is only one number left we have found what is called the digital root. In other words, the sum of the digits of a number is called its digital root. Example: For 5674, 5 + 6 + 7 + 4 = 22 and 2 + 2 = 4 » 4 is the digital root of 5674
The digital root is useful as it helps us check the accuracy of our arithmetic, and can also check divisibility by 3 and 9.
===
[digital_root(n) =[def]= n%9]
===
Fermat numbers:
    [Fermat_numbers[0] == 3]
    [[i>=1] -> [Fermat_numbers[i] == (Fermat_numbers[i-1]-1)**2+1]]
    [5 == ((3-1)**2+1)%9]
    [8 == ((5-1)**2+1)%9]
    [5 == ((8-1)**2+1)%9]
    [[i>=1] -> [Fermat_numbers[i]%9 <- {5,8}]]
    [[i>=1] -> [Fermat_numbers[2*i-1]%9 == 5]]
    [[i>=1] -> [Fermat_numbers[2*i]%9 == 8]]
]]
[[[
https://oeis.org/A000215
===
A000215		Fermat numbers: a(n) = 2^(2^n) + 1.
(Formerly M2503 N0990)		227
3, 5, 17, 257, 65537, 4294967297, 18446744073709551617, 340282366920938463463374607431768211457, 115792089237316195423570985008687907853269984665640564039457584007913129639937 (list; graph; refs; listen; history; text; internal format)
OFFSET	
0,1

COMMENTS	
It is conjectured that just the first 5 numbers in this sequence are primes.

An infinite coprime sequence defined by recursion. - Michael Somos, Mar 14 2004

For n>0, Fermat numbers F(n) have digital roots 5 or 8 depending on whether n is even or odd (Koshy). - Lekraj Beedassy, Mar 17 2005

This is the special case k=2 of sequences with exact mutual k-residues. In general, a(1)=k+1 and a(n)=min{m | m>a(n-1), mod(m,a(i))=k, i=1,...,n-1}. k=1 gives Sylvester's sequence A000058. - Seppo Mustonen, Sep 04 2005

For n>1 final two digits of a(n) are periodically repeated with period 4: {17, 57, 37, 97}. - Alexander Adamchuk, Apr 07 2007

For 1 < k <= 2^n, a(A007814(k-1)) divides a(n) + 2^k. More generally, for any number k, let r = k mod 2^n and suppose r != 1, then a(A007814(r-1)) divides a(n) + 2^k. - T. D. Noe, Jul 12 2007

A000120(a(n)) = 2. - Reinhard Zumkeller, Aug 07 2010

From Daniel Forgues, Jun 20 2011: (Start)

The Fermat numbers F_n are F_n(a,b) = a^(2^n) + b^(2^n) with a = 2 and b = 1.

All factors of F_n = 2^(2^n) + 1 are of the form k*(2^n) + 1, k >= 1.

The products of distinct Fermat numbers (in their binary representation, see A080176) give rows of Sierpiński's triangle (A006943). (End)

Let F(n) be a Fermat number. For n > 2, F(n) is prime if and only if 5^((F(n)-1)/4) == sqrt(F(n)-1) (mod F(n)). - Arkadiusz Wesolowski, Jul 16 2011

Conjecture: let the smallest prime factor of Fermat number F(n) be P(F(n)). If F(n) is composite, then P(F(n)) < 3*2^(2^n/2 - n - 2). - Arkadiusz Wesolowski, Aug 10 2012

The Fermat primes are not Brazilian numbers, so they belong to A220627, but the Fermat composites are Brazilian numbers so they belong to A220571. For a proof, see Proposition 3 page 36 on "Les nombres brésiliens" in Links. - Bernard Schott, Dec 29 2012

It appears that this sequence is generated by starting with a(0)=3 and following the rule "Write in binary and read in base 4".  For an example of "Write in binary and read in ternary", see A014118. - John W. Layman, Jul 30 2013

Conjecture: the numbers > 5 in this sequence, i.e., 2^2^k + 1 for k>1, are exactly the numbers n such that (n-1)^4-1 divides 2^(n-1)-1. - M. F. Hasler, Jul 24 2015

REFERENCES	
M. Aigner and G. M. Ziegler, Proofs from The Book, Springer-Verlag, Berlin, 2nd. ed., 2001; see p. 3.

T. M. Apostol, Introduction to Analytic Number Theory, Springer-Verlag, 1976, page 7.

P. Bachmann, Niedere Zahlentheorie (1902, 1910), reprinted Chelsea, NY, 1968, vol. 2, p. 87.

James Gleick, Faster, Vintage Books, NY, 2000 (see pp. 259-261).

R. K. Guy, Unsolved Problems in Number Theory, A3.

G. H. Hardy and E. M. Wright, An Introduction to the Theory of Numbers. 3rd ed., Oxford Univ. Press, 1954, p. 14.

E. Hille, Analytic Function Theory, Vol. I, Chelsea, N.Y., see p. 64.

T. Koshy, "The Digital Root Of A Fermat Number", Journal of Recreational Mathematics Vol. 32 No. 2 2002-3 Baywood NY.

M. Krizek, F. Luca & L. Somer, 17 Lectures on Fermat Numbers, Springer-Verlag NY 2001.

C. S. Ogilvy and J. T. Anderson, Excursions in Number Theory, Oxford University Press, NY, 1966, p. 36.

Clifford A. Pickover, A Passion for Mathematics, Wiley, 2005; see pp. 18, 59.

C. A. Pickover, The Math Book, Sterling, NY, 2009; see p. 202.

N. J. A. Sloane, A Handbook of Integer Sequences, Academic Press, 1973 (includes this sequence).

N. J. A. Sloane and Simon Plouffe, The Encyclopedia of Integer Sequences, Academic Press, 1995 (includes this sequence).

David Wells, The Penguin Dictionary of Curious and Interesting Numbers, Penguin Books, 1987, pp. 148-149.

LINKS	
N. J. A. Sloane, Table of n, a(n) for n = 0..11

Richard Bellman, A note on relatively prime sequences, Bull. Amer. Math. Soc. 53 (1947), 778-779.

C. K. Caldwell, The Prime Glossary, Fermat number.

C. K. Caldwell, The prime pages All prime-square Mersenne divisors are Wieferich (2021).

Shane Chern, Fermat Numbers in Multinomial Coefficients, J. Int. Seq. 17 (2014) # 14.3.2.

Leonhard Euler, Observations on a theorem of Fermat and others on looking at prime numbers, arXiv:math/0501118 [math.HO], 2005-2008.

Leonhard Euler, Observationes de theoremate quodam Fermatiano aliisque ad numeros primos spectantibus.

Emmanuel Ferrand, Deformations of the Taylor Formula, Journal of Integer Sequences, Vol. 10 (2007), Article 07.1.7.

Richard K. Guy, The strong law of small numbers. Amer. Math. Monthly 95 (1988), no. 8, 697-712. [Annotated scanned copy]

Wilfrid Keller, Prime factors k.2^n + 1 of Fermat numbers F_m

T.-W. Leung, A Brief Introduction to Fermat Numbers

Romeo Meštrović, Euclid's theorem on the infinitude of primes: a historical survey of its proofs (300 BC--2012) and another new proof, arXiv preprint arXiv:1202.3670 [math.HO], 2012. - From N. J. A. Sloane, Jun 13 2012

Romeo Meštrović, Goldbach-type conjectures arising from some arithmetic progressions, University of Montenegro, 2018.

Romeo Meštrović, Goldbach's like conjectures arising from arithmetic progressions whose first two terms are primes, arXiv:1901.07882 [math.NT], 2019.

Michael A. Morrison and John Brillhart, The factorization of F_7, Bull. Amer. Math. Soc. 77 (1971), 264.

Robert Munafo, Fermat Numbers

Robert Munafo, Notes on Fermat numbers

Seppo Mustonen, On integer sequences with mutual k-residues.

Seppo Mustonen, On integer sequences with mutual k-residues. [Local copy]

OEIS Wiki, Fermat numbers.

OEIS Wiki, Sierpinski's triangle.

G. A. Paxson, The compositeness of the thirteenth Fermat number, Math. Comp. 15 (76) (1961) 420-420.

Carl Pomerance, A tale of two sieves, Notices Amer. Math. Soc., 43 (1996), 1473-1485.

P. Sanchez, PlanetMath.org, Fermat Numbers

Bernard Schott, Les nombres brésiliens, Quadrature, no. 76, avril-juin 2010, pages 30-38. Local copy, included here with permission from the editors of Quadrature.

G. Villemin's Almanach of Numbers, Nombres de Fermat.

Le Roy J. Warren, Henry G. Bray, On the square-freeness of Fermat and Mersenne Numbers, Pac. J. Math. 22 (3) (1967) 563.

Eric Weisstein's World of Mathematics, Fermat Number.

Eric Weisstein's World of Mathematics, Generalized Fermat Number.

Wikipedia, Fermat number.

Wolfram Research, Fermat numbers are pairwise coprime.

FORMULA	
a(0) = 3; a(n) = (a(n-1)-1)^2 + 1, n >= 1.

a(n) = a(n-1)*a(n-2)*...*a(1)*a(0) + 2, n >= 0, where for n = 0, we get the empty product, i.e., 1, plus 2, giving 3 = a(0). - Benoit Cloitre, Sep 15 2002 [edited by Daniel Forgues, Jun 20 2011]

The above formula implies that the Fermat numbers (being all odd) are coprime.

Conjecture: F is a Fermat prime if and only if phi(F-2) = (F-1)/2. - Benoit Cloitre, Sep 15 2002

If a(n) is composite, then a(n) = A242619(n)^2 + A242620(n)^2 = A257916(n)^2 - A257917(n)^2. - Arkadiusz Wesolowski, May 13 2015

Sum_{n>=0} 1/a(n) = A051158. - Amiram Eldar, Oct 27 2020

From Amiram Eldar, Jan 28 2021: (Start)

Product_{n>=0} (1 + 1/a(n)) = A249119.

Product_{n>=0} (1 - 1/a(n)) = 1/2. (End)

EXAMPLE	
a(0) = 1*2^1 + 1 = 3 = 1*(2*1) + 1.

a(1) = 1*2^2 + 1 = 5 = 1*(2*2) + 1.

a(2) = 1*2^4 + 1 = 17 = 2*(2*4) + 1.

a(3) = 1*2^8 + 1 = 257 = 16*(2*8) + 1.

a(4) = 1*2^16 + 1 = 65537 = 2048*(2*16) + 1.

a(5) = 1*2^32 + 1 = 4294967297 = 641*6700417 = (10*(2*32) + 1)*(104694*(2*32) + 1).

a(6) = 1*2^64 + 1 = 18446744073709551617 = 274177*67280421310721 = (2142*(2*64) + 1)*(525628291490*(2*64) + 1).

MAPLE	
A000215 := n->2^(2^n)+1;

MATHEMATICA	
Table[2^(2^n) + 1, {n, 0, 8}] (* Alonso del Arte, Jun 07 2011 *)

PROG	
(PARI) a(n)=if(n<1, 3*(n==0), (a(n-1)-1)^2+1)

(Maxima) A000215(n):=2^(2^n)+1$ makelist(A000215(n), n, 0, 10); /* Martin Ettl, Dec 10 2012 */

(Haskell)

a000215 = (+ 1) . (2 ^) . (2 ^)  -- Reinhard Zumkeller, Feb 13 2015

(Python)

def a(n): return 2**(2**n) + 1

print([a(n) for n in range(9)]) # Michael S. Branicky, Apr 19 2021

CROSSREFS	
a(n) = A001146(n) + 1 = A051179(n) + 2.

Cf. A019434, A050922, A051158, A051179, A063486, A073617, A085866.

See A004249 for a similar sequence.

Cf. A080176 for binary representation of Fermat numbers.

Cf. A220627, A220570, A220571, A125134, A249119.

Sequence in context: A272061 A247203 A262534 * A339344 A263539 A123599

Adjacent sequences:  A000212 A000213 A000214 * A000216 A000217 A000218

KEYWORD	
nonn,easy,nice

AUTHOR	
N. J. A. Sloane

STATUS	
approved

]]]




#]]]'''
__all__ = '''
    Fermat_exponents

    '''.split()

Fermat_exponents = (*range(5),)
Fermat_primes = (*(2**2**e+1 for e in Fermat_exponents),)

#print(Fermat_primes)
assert Fermat_primes == (3, 5, 17, 257, 65537)


