r'''[[[
e ../../python3_src/nn_ns/CJK/CJK_pinyin__ucd/read_CJK汉字拼音表_更新_42856字.py

nn_ns.CJK.CJK_pinyin__ucd.read_CJK汉字拼音表_更新_42856字
py -m nn_ns.CJK.CJK_pinyin__ucd.read_CJK汉字拼音表_更新_42856字 -o ../../python3_src/nn_ns/CJK/CJK_pinyin__ucd/hanzi2pinyins.py --use_version=1
du -h ../../python3_src/nn_ns/CJK/CJK_pinyin__ucd/hanzi2pinyins.py
    868K

view ../../python3_src/nn_ns/CJK/CJK_pinyin__ucd/hanzi2pinyins.py
py -m nn_ns.CJK.CJK_pinyin__ucd.hanzi2pinyins
py -m nn_ns.CJK.CJK_pinyin__ucd.read_CJK汉字拼音表_更新_42856字 -o ../../python3_src/nn_ns/CJK/CJK_pinyin__ucd/hanzi2pinyins.py --use_version=2
du -h ../../python3_src/nn_ns/CJK/CJK_pinyin__ucd/hanzi2pinyins.py
    188K

py -m nn_ns.CJK.CJK_pinyin__ucd.read_CJK汉字拼音表_更新_42856字 -o ../../python3_src/nn_ns/CJK/CJK_pinyin__ucd/hanzi2pinyins.py --use_version=3
    264K

#]]]'''

__all__ = '''
    read_CJK汉字拼音表_更新_42856字
    '''.split()

import re
'''
㐀 qiū（qiu1）
...
㐤 dān qiú（dan1 qiu2）

######################## ' ' or '/'
'''
rex_line = re.compile(r'(?P<hanzi>\S) [^（]+（(?P<pinyins>[^）]+)）')
def read_CJK汉字拼音表_更新_42856字(ifile):
    it = iter(ifile); del ifile

    hanzi2pinyins = {}
    for i, line in zip(range(47), it):pass
    for i, line in enumerate(it, i+1):
        line = line.rstrip()
        if not (len(line) > 2 and line[0] != '◆'):
            continue
        m = rex_line.fullmatch(line)
        if m is None: raise Exception(f'line{i} is bad: {line!r}')
        hanzi = m['hanzi']
        pinyins = m['pinyins']
        pinyins = sorted(pinyins.replace('/', ' ').split())
        hanzi2pinyins[hanzi] = pinyins

    assert '㐀' in hanzi2pinyins
    return hanzi2pinyins


class Global:
    ifname = '●CJK汉字拼音表_更新_42856字.txt'
    encoding = 'utf_16_le'
    ofname = 'hanzi2pinyins.py'


def main(args=None):
    from nn_ns.CJK.CJK_common.save_load_hanzi2pinyins import save8py_src
    import argparse
    from seed.io.may_open import may_open_stdout # may_open_stdin
    from pprint import pprint
    from pathlib import PurePath as Path
    this_file = Path(__file__)
    this_folder = this_file.parent
    this_file_name = this_file.name

    parser = argparse.ArgumentParser(
        description=f'read “{Global.ifname}”'
        , epilog=''
        , formatter_class=argparse.RawDescriptionHelpFormatter
        )
    parser.add_argument('--use_version', type=int, default=3, choices=[1,2, 3]
                        , help='select impl version')

    parser.add_argument('-i', '--input', type=str, default=None
                        , help='input file path')
    parser.add_argument('-o', '--output', type=str, default=None
                        , help='output file path')
    parser.add_argument('-ie', '--input_encoding', type=str
                        , default=Global.encoding
                        , help='input file encoding')
    parser.add_argument('-oe', '--output_encoding', type=str
                        , default='utf8'
                        , help='output file encoding')
    parser.add_argument('-f', '--force', action='store_true'
                        , default = False
                        , help='open mode for output file')

    args = parser.parse_args(args)
    version = args.use_version
    input_encoding = args.input_encoding
    output_encoding = args.output_encoding
    omode = 'wt' if args.force else 'xt'

    may_ifname = args.input
    if may_ifname is None:
        ifname = this_folder / Global.ifname
    else:
        ifname = may_ifname
    with open(ifname, 'rt', encoding=input_encoding) as fin:
        hanzi2pinyins = read_CJK汉字拼音表_更新_42856字(fin)
    assert '㐀' in hanzi2pinyins
    if version in [2,3]:
        partition_by_single_pinyin = version==3
        whole_txt = save8py_src(hanzi2pinyins, nm4varable4hanzi2pinyins='hanzi2pinyins', nm4data_mkr=this_file_name, partition_by_single_pinyin=partition_by_single_pinyin)

    may_ofname = args.output
    if may_ofname is None:
        may_ofname = this_folder / Global.ofname
    with may_open_stdout(may_ofname, omode, encoding=output_encoding) as fout:
        if version in [2,3]:
            print(whole_txt, file=fout);
        else:
            print(f'#hanzi2pinyins generated by {this_file_name}', file=fout);
            print('hanzi2pinyins = \\', file=fout);
            pprint(hanzi2pinyins, stream=fout)


if __name__ == '__main__':
    main()

