#__all__:goto
r'''[[[
e ../../python3_src/nn_ns/CJK/CJK_data/raw/拼音用字.py

[[
拼音用字:带音调字母:
===
拼音用字囗带音调字母='=aāáǎà=AĀÁǍÀ=oōóǒò=OŌÓǑÒ=eēéěè=EĒÉĚÈ=iīíǐì=IĪÍǏÌ=uūúǔù=UŪÚǓÙ=üǖǘǚǜ=ÜǕǗǙǛ=nńňǹ=NŃŇǸ=mḿ=MḾ=gḡǵǧ=GḠǴǦ='
===
a
ā:0x101:LATIN SMALL LETTER A WITH MACRON
á:0xe1:LATIN SMALL LETTER A WITH ACUTE
ǎ:0x1ce:LATIN SMALL LETTER A WITH CARON
à:0xe0:LATIN SMALL LETTER A WITH GRAVE
Ā:0x100:LATIN CAPITAL LETTER A WITH MACRON
Á:0xc1:LATIN CAPITAL LETTER A WITH ACUTE
Ǎ:0x1cd:LATIN CAPITAL LETTER A WITH CARON
À:0xc0:LATIN CAPITAL LETTER A WITH GRAVE

===
o
ō:0x14d:LATIN SMALL LETTER O WITH MACRON
ó:0xf3:LATIN SMALL LETTER O WITH ACUTE
ǒ:0x1d2:LATIN SMALL LETTER O WITH CARON
ò:0xf2:LATIN SMALL LETTER O WITH GRAVE
Ō:0x14c:LATIN CAPITAL LETTER O WITH MACRON
Ó:0xd3:LATIN CAPITAL LETTER O WITH ACUTE
Ǒ:0x1d1:LATIN CAPITAL LETTER O WITH CARON
Ò:0xd2:LATIN CAPITAL LETTER O WITH GRAVE

===
e
ē:0x113:LATIN SMALL LETTER E WITH MACRON
é:0xe9:LATIN SMALL LETTER E WITH ACUTE
ě:0x11b:LATIN SMALL LETTER E WITH CARON
è:0xe8:LATIN SMALL LETTER E WITH GRAVE
Ē:0x112:LATIN CAPITAL LETTER E WITH MACRON
É:0xc9:LATIN CAPITAL LETTER E WITH ACUTE
Ě:0x11a:LATIN CAPITAL LETTER E WITH CARON
È:0xc8:LATIN CAPITAL LETTER E WITH GRAVE

===
i
ī:0x12b:LATIN SMALL LETTER I WITH MACRON
í:0xed:LATIN SMALL LETTER I WITH ACUTE
ǐ:0x1d0:LATIN SMALL LETTER I WITH CARON
ì:0xec:LATIN SMALL LETTER I WITH GRAVE
Ī:0x12a:LATIN CAPITAL LETTER I WITH MACRON
Í:0xcd:LATIN CAPITAL LETTER I WITH ACUTE
Ǐ:0x1cf:LATIN CAPITAL LETTER I WITH CARON
Ì:0xcc:LATIN CAPITAL LETTER I WITH GRAVE

===
u
ū:0x16b:LATIN SMALL LETTER U WITH MACRON
ú:0xfa:LATIN SMALL LETTER U WITH ACUTE
ǔ:0x1d4:LATIN SMALL LETTER U WITH CARON
ù:0xf9:LATIN SMALL LETTER U WITH GRAVE
Ū:0x16a:LATIN CAPITAL LETTER U WITH MACRON
Ú:0xda:LATIN CAPITAL LETTER U WITH ACUTE
Ǔ:0x1d3:LATIN CAPITAL LETTER U WITH CARON
Ù:0xd9:LATIN CAPITAL LETTER U WITH GRAVE

===
ü:0xfc:LATIN SMALL LETTER U WITH DIAERESIS
ǖ:0x1d6:LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
ǘ:0x1d8:LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
ǚ:0x1da:LATIN SMALL LETTER U WITH DIAERESIS AND CARON
ǜ:0x1dc:LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE

Ü:0xdc:LATIN CAPITAL LETTER U WITH DIAERESIS
Ǖ:0x1d5:LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
Ǘ:0x1d7:LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
Ǚ:0x1d9:LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
Ǜ:0x1db:LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE

===
n
ń:0x144:LATIN SMALL LETTER N WITH ACUTE
ň:0x148:LATIN SMALL LETTER N WITH CARON
ǹ:0x1f9:LATIN SMALL LETTER N WITH GRAVE
Ń:0x143:LATIN CAPITAL LETTER N WITH ACUTE
Ň:0x147:LATIN CAPITAL LETTER N WITH CARON
Ǹ:0x1f8:LATIN CAPITAL LETTER N WITH GRAVE

===
m
ḿ:0x1e3f:LATIN SMALL LETTER M WITH ACUTE
Ḿ:0x1e3e:LATIN CAPITAL LETTER M WITH ACUTE

===
g
ḡ:0x1e21:LATIN SMALL LETTER G WITH MACRON
ǵ:0x1f5:LATIN SMALL LETTER G WITH ACUTE
ǧ:0x1e7:LATIN SMALL LETTER G WITH CARON
Ḡ:0x1e20:LATIN CAPITAL LETTER G WITH MACRON
Ǵ:0x1f4:LATIN CAPITAL LETTER G WITH ACUTE
Ǧ:0x1e6:LATIN CAPITAL LETTER G WITH CARON

===
]]


nn_ns.CJK.CJK_data.raw.拼音用字
py -m nn_ns.app.debug_cmd   nn_ns.CJK.CJK_data.raw.拼音用字 -x
py -m nn_ns.app.doctest_cmd nn_ns.CJK.CJK_data.raw.拼音用字:__doc__ -ff -v
from nn_ns.CJK.CJK_data.raw.拼音用字 import 打印拼音用字囗按名字囗, 找出拼音用字囗按名字囗, 拼音用字囗带音调字母



[[
view ../../python3_src/nn_ns/CJK/CJK_common/is_hz.py
===
汉语字典囗
    拼音用字:àáèéìíòóùúüāēěīńňōūǎǐǒǔǘǚǜɑɡˇˉˊˋ
汉语辞海囗:
    拼音用字:àáèéêìíòó÷ùúüāēěīňōūǎǐǒǔǚǜ
现代汉语词典囗第五版囗文本囗
    拼音用字:ÀÁÅÈÉ×àáèéêìíñòóö÷ùúüĀāĂĒēĔěīńňŌōūǎǐǒǔǘǚǜɑɡˇˊˋề

整理:拼音用字:āáǎà ēéěè īíǐì ōóǒò ūúǔù üǘǚǜ ê ńň  ĀÁĂÀ ĒÉĔÈ ÅŌöñ

ch2nm ê üǚ ēéěè ĒÉĔÈ
ê
'LATIN SMALL LETTER E WITH CIRCUMFLEX'
ü
'LATIN SMALL LETTER U WITH DIAERESIS'
ǚ
'LATIN SMALL LETTER U WITH DIAERESIS AND CARON'
ē
'LATIN SMALL LETTER E WITH MACRON'
é
'LATIN SMALL LETTER E WITH ACUTE'
ě
'LATIN SMALL LETTER E WITH CARON'
è
'LATIN SMALL LETTER E WITH GRAVE'
Ē
'LATIN CAPITAL LETTER E WITH MACRON'
É
'LATIN CAPITAL LETTER E WITH ACUTE'
Ĕ
'LATIN CAPITAL LETTER E WITH BREVE'
    why? not 『CARON』见下面:[Ĕ_vs_Ě]
È
'LATIN CAPITAL LETTER E WITH GRAVE'

===
Ĕ_vs_Ě
Ĕ:0x114:LATIN CAPITAL LETTER E WITH BREVE
Ě:0x11a:LATIN CAPITAL LETTER E WITH CARON
]]


[[[
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full=True
===
ä:0xe4:LATIN SMALL LETTER A WITH DIAERESIS
ë:0xeb:LATIN SMALL LETTER E WITH DIAERESIS
ḧ:0x1e27:LATIN SMALL LETTER H WITH DIAERESIS
ï:0xef:LATIN SMALL LETTER I WITH DIAERESIS
ö:0xf6:LATIN SMALL LETTER O WITH DIAERESIS
ẗ:0x1e97:LATIN SMALL LETTER T WITH DIAERESIS
ü:0xfc:LATIN SMALL LETTER U WITH DIAERESIS
ẅ:0x1e85:LATIN SMALL LETTER W WITH DIAERESIS
ẍ:0x1e8d:LATIN SMALL LETTER X WITH DIAERESIS
ÿ:0xff:LATIN SMALL LETTER Y WITH DIAERESIS
â:0xe2:LATIN SMALL LETTER A WITH CIRCUMFLEX
ĉ:0x109:LATIN SMALL LETTER C WITH CIRCUMFLEX
ê:0xea:LATIN SMALL LETTER E WITH CIRCUMFLEX
ĝ:0x11d:LATIN SMALL LETTER G WITH CIRCUMFLEX
ĥ:0x125:LATIN SMALL LETTER H WITH CIRCUMFLEX
î:0xee:LATIN SMALL LETTER I WITH CIRCUMFLEX
ĵ:0x135:LATIN SMALL LETTER J WITH CIRCUMFLEX
ô:0xf4:LATIN SMALL LETTER O WITH CIRCUMFLEX
ŝ:0x15d:LATIN SMALL LETTER S WITH CIRCUMFLEX
û:0xfb:LATIN SMALL LETTER U WITH CIRCUMFLEX
ŵ:0x175:LATIN SMALL LETTER W WITH CIRCUMFLEX
ŷ:0x177:LATIN SMALL LETTER Y WITH CIRCUMFLEX
ẑ:0x1e91:LATIN SMALL LETTER Z WITH CIRCUMFLEX
ā:0x101:LATIN SMALL LETTER A WITH MACRON
ē:0x113:LATIN SMALL LETTER E WITH MACRON
ḡ:0x1e21:LATIN SMALL LETTER G WITH MACRON
ī:0x12b:LATIN SMALL LETTER I WITH MACRON
ō:0x14d:LATIN SMALL LETTER O WITH MACRON
ū:0x16b:LATIN SMALL LETTER U WITH MACRON
ȳ:0x233:LATIN SMALL LETTER Y WITH MACRON
á:0xe1:LATIN SMALL LETTER A WITH ACUTE
ć:0x107:LATIN SMALL LETTER C WITH ACUTE
é:0xe9:LATIN SMALL LETTER E WITH ACUTE
ǵ:0x1f5:LATIN SMALL LETTER G WITH ACUTE
í:0xed:LATIN SMALL LETTER I WITH ACUTE
ḱ:0x1e31:LATIN SMALL LETTER K WITH ACUTE
ĺ:0x13a:LATIN SMALL LETTER L WITH ACUTE
ḿ:0x1e3f:LATIN SMALL LETTER M WITH ACUTE
ń:0x144:LATIN SMALL LETTER N WITH ACUTE
ó:0xf3:LATIN SMALL LETTER O WITH ACUTE
ṕ:0x1e55:LATIN SMALL LETTER P WITH ACUTE
ŕ:0x155:LATIN SMALL LETTER R WITH ACUTE
ś:0x15b:LATIN SMALL LETTER S WITH ACUTE
ú:0xfa:LATIN SMALL LETTER U WITH ACUTE
ẃ:0x1e83:LATIN SMALL LETTER W WITH ACUTE
ý:0xfd:LATIN SMALL LETTER Y WITH ACUTE
ź:0x17a:LATIN SMALL LETTER Z WITH ACUTE
ǎ:0x1ce:LATIN SMALL LETTER A WITH CARON
č:0x10d:LATIN SMALL LETTER C WITH CARON
ď:0x10f:LATIN SMALL LETTER D WITH CARON
ě:0x11b:LATIN SMALL LETTER E WITH CARON
ǧ:0x1e7:LATIN SMALL LETTER G WITH CARON
ȟ:0x21f:LATIN SMALL LETTER H WITH CARON
ǐ:0x1d0:LATIN SMALL LETTER I WITH CARON
ǰ:0x1f0:LATIN SMALL LETTER J WITH CARON
ǩ:0x1e9:LATIN SMALL LETTER K WITH CARON
ľ:0x13e:LATIN SMALL LETTER L WITH CARON
ň:0x148:LATIN SMALL LETTER N WITH CARON
ǒ:0x1d2:LATIN SMALL LETTER O WITH CARON
ř:0x159:LATIN SMALL LETTER R WITH CARON
š:0x161:LATIN SMALL LETTER S WITH CARON
ť:0x165:LATIN SMALL LETTER T WITH CARON
ǔ:0x1d4:LATIN SMALL LETTER U WITH CARON
ž:0x17e:LATIN SMALL LETTER Z WITH CARON
à:0xe0:LATIN SMALL LETTER A WITH GRAVE
è:0xe8:LATIN SMALL LETTER E WITH GRAVE
ì:0xec:LATIN SMALL LETTER I WITH GRAVE
ǹ:0x1f9:LATIN SMALL LETTER N WITH GRAVE
ò:0xf2:LATIN SMALL LETTER O WITH GRAVE
ù:0xf9:LATIN SMALL LETTER U WITH GRAVE
ẁ:0x1e81:LATIN SMALL LETTER W WITH GRAVE
ỳ:0x1ef3:LATIN SMALL LETTER Y WITH GRAVE
ă:0x103:LATIN SMALL LETTER A WITH BREVE
ĕ:0x115:LATIN SMALL LETTER E WITH BREVE
ğ:0x11f:LATIN SMALL LETTER G WITH BREVE
ĭ:0x12d:LATIN SMALL LETTER I WITH BREVE
ŏ:0x14f:LATIN SMALL LETTER O WITH BREVE
ŭ:0x16d:LATIN SMALL LETTER U WITH BREVE
Ä:0xc4:LATIN CAPITAL LETTER A WITH DIAERESIS
Ë:0xcb:LATIN CAPITAL LETTER E WITH DIAERESIS
Ḧ:0x1e26:LATIN CAPITAL LETTER H WITH DIAERESIS
Ï:0xcf:LATIN CAPITAL LETTER I WITH DIAERESIS
Ö:0xd6:LATIN CAPITAL LETTER O WITH DIAERESIS
Ü:0xdc:LATIN CAPITAL LETTER U WITH DIAERESIS
Ẅ:0x1e84:LATIN CAPITAL LETTER W WITH DIAERESIS
Ẍ:0x1e8c:LATIN CAPITAL LETTER X WITH DIAERESIS
Ÿ:0x178:LATIN CAPITAL LETTER Y WITH DIAERESIS
Â:0xc2:LATIN CAPITAL LETTER A WITH CIRCUMFLEX
Ĉ:0x108:LATIN CAPITAL LETTER C WITH CIRCUMFLEX
Ê:0xca:LATIN CAPITAL LETTER E WITH CIRCUMFLEX
Ĝ:0x11c:LATIN CAPITAL LETTER G WITH CIRCUMFLEX
Ĥ:0x124:LATIN CAPITAL LETTER H WITH CIRCUMFLEX
Î:0xce:LATIN CAPITAL LETTER I WITH CIRCUMFLEX
Ĵ:0x134:LATIN CAPITAL LETTER J WITH CIRCUMFLEX
Ô:0xd4:LATIN CAPITAL LETTER O WITH CIRCUMFLEX
Ŝ:0x15c:LATIN CAPITAL LETTER S WITH CIRCUMFLEX
Û:0xdb:LATIN CAPITAL LETTER U WITH CIRCUMFLEX
Ŵ:0x174:LATIN CAPITAL LETTER W WITH CIRCUMFLEX
Ŷ:0x176:LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
Ẑ:0x1e90:LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
Ā:0x100:LATIN CAPITAL LETTER A WITH MACRON
Ē:0x112:LATIN CAPITAL LETTER E WITH MACRON
Ḡ:0x1e20:LATIN CAPITAL LETTER G WITH MACRON
Ī:0x12a:LATIN CAPITAL LETTER I WITH MACRON
Ō:0x14c:LATIN CAPITAL LETTER O WITH MACRON
Ū:0x16a:LATIN CAPITAL LETTER U WITH MACRON
Ȳ:0x232:LATIN CAPITAL LETTER Y WITH MACRON
Á:0xc1:LATIN CAPITAL LETTER A WITH ACUTE
Ć:0x106:LATIN CAPITAL LETTER C WITH ACUTE
É:0xc9:LATIN CAPITAL LETTER E WITH ACUTE
Ǵ:0x1f4:LATIN CAPITAL LETTER G WITH ACUTE
Í:0xcd:LATIN CAPITAL LETTER I WITH ACUTE
Ḱ:0x1e30:LATIN CAPITAL LETTER K WITH ACUTE
Ĺ:0x139:LATIN CAPITAL LETTER L WITH ACUTE
Ḿ:0x1e3e:LATIN CAPITAL LETTER M WITH ACUTE
Ń:0x143:LATIN CAPITAL LETTER N WITH ACUTE
Ó:0xd3:LATIN CAPITAL LETTER O WITH ACUTE
Ṕ:0x1e54:LATIN CAPITAL LETTER P WITH ACUTE
Ŕ:0x154:LATIN CAPITAL LETTER R WITH ACUTE
Ś:0x15a:LATIN CAPITAL LETTER S WITH ACUTE
Ú:0xda:LATIN CAPITAL LETTER U WITH ACUTE
Ẃ:0x1e82:LATIN CAPITAL LETTER W WITH ACUTE
Ý:0xdd:LATIN CAPITAL LETTER Y WITH ACUTE
Ź:0x179:LATIN CAPITAL LETTER Z WITH ACUTE
Ǎ:0x1cd:LATIN CAPITAL LETTER A WITH CARON
Č:0x10c:LATIN CAPITAL LETTER C WITH CARON
Ď:0x10e:LATIN CAPITAL LETTER D WITH CARON
Ě:0x11a:LATIN CAPITAL LETTER E WITH CARON
Ǧ:0x1e6:LATIN CAPITAL LETTER G WITH CARON
Ȟ:0x21e:LATIN CAPITAL LETTER H WITH CARON
Ǐ:0x1cf:LATIN CAPITAL LETTER I WITH CARON
Ǩ:0x1e8:LATIN CAPITAL LETTER K WITH CARON
Ľ:0x13d:LATIN CAPITAL LETTER L WITH CARON
Ň:0x147:LATIN CAPITAL LETTER N WITH CARON
Ǒ:0x1d1:LATIN CAPITAL LETTER O WITH CARON
Ř:0x158:LATIN CAPITAL LETTER R WITH CARON
Š:0x160:LATIN CAPITAL LETTER S WITH CARON
Ť:0x164:LATIN CAPITAL LETTER T WITH CARON
Ǔ:0x1d3:LATIN CAPITAL LETTER U WITH CARON
Ž:0x17d:LATIN CAPITAL LETTER Z WITH CARON
À:0xc0:LATIN CAPITAL LETTER A WITH GRAVE
È:0xc8:LATIN CAPITAL LETTER E WITH GRAVE
Ì:0xcc:LATIN CAPITAL LETTER I WITH GRAVE
Ǹ:0x1f8:LATIN CAPITAL LETTER N WITH GRAVE
Ò:0xd2:LATIN CAPITAL LETTER O WITH GRAVE
Ù:0xd9:LATIN CAPITAL LETTER U WITH GRAVE
Ẁ:0x1e80:LATIN CAPITAL LETTER W WITH GRAVE
Ỳ:0x1ef2:LATIN CAPITAL LETTER Y WITH GRAVE
Ă:0x102:LATIN CAPITAL LETTER A WITH BREVE
Ĕ:0x114:LATIN CAPITAL LETTER E WITH BREVE
Ğ:0x11e:LATIN CAPITAL LETTER G WITH BREVE
Ĭ:0x12c:LATIN CAPITAL LETTER I WITH BREVE
Ŏ:0x14e:LATIN CAPITAL LETTER O WITH BREVE
Ŭ:0x16c:LATIN CAPITAL LETTER U WITH BREVE
ǟ:0x1df:LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
ȫ:0x22b:LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
ǖ:0x1d6:LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
ḯ:0x1e2f:LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
ǘ:0x1d8:LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
ǚ:0x1da:LATIN SMALL LETTER U WITH DIAERESIS AND CARON
ǜ:0x1dc:LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
Ǟ:0x1de:LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
Ȫ:0x22a:LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
Ǖ:0x1d5:LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
Ḯ:0x1e2e:LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
Ǘ:0x1d7:LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
Ǚ:0x1d9:LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
Ǜ:0x1db:LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
]]]
[[[
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full=False
===
ä:0xe4:LATIN SMALL LETTER A WITH DIAERESIS
ö:0xf6:LATIN SMALL LETTER O WITH DIAERESIS
ë:0xeb:LATIN SMALL LETTER E WITH DIAERESIS
ï:0xef:LATIN SMALL LETTER I WITH DIAERESIS
ü:0xfc:LATIN SMALL LETTER U WITH DIAERESIS
â:0xe2:LATIN SMALL LETTER A WITH CIRCUMFLEX
ô:0xf4:LATIN SMALL LETTER O WITH CIRCUMFLEX
ê:0xea:LATIN SMALL LETTER E WITH CIRCUMFLEX
î:0xee:LATIN SMALL LETTER I WITH CIRCUMFLEX
û:0xfb:LATIN SMALL LETTER U WITH CIRCUMFLEX
ĝ:0x11d:LATIN SMALL LETTER G WITH CIRCUMFLEX
ā:0x101:LATIN SMALL LETTER A WITH MACRON
ō:0x14d:LATIN SMALL LETTER O WITH MACRON
ē:0x113:LATIN SMALL LETTER E WITH MACRON
ī:0x12b:LATIN SMALL LETTER I WITH MACRON
ū:0x16b:LATIN SMALL LETTER U WITH MACRON
ḡ:0x1e21:LATIN SMALL LETTER G WITH MACRON
á:0xe1:LATIN SMALL LETTER A WITH ACUTE
ó:0xf3:LATIN SMALL LETTER O WITH ACUTE
é:0xe9:LATIN SMALL LETTER E WITH ACUTE
í:0xed:LATIN SMALL LETTER I WITH ACUTE
ú:0xfa:LATIN SMALL LETTER U WITH ACUTE
ń:0x144:LATIN SMALL LETTER N WITH ACUTE
ḿ:0x1e3f:LATIN SMALL LETTER M WITH ACUTE
ǵ:0x1f5:LATIN SMALL LETTER G WITH ACUTE
ǎ:0x1ce:LATIN SMALL LETTER A WITH CARON
ǒ:0x1d2:LATIN SMALL LETTER O WITH CARON
ě:0x11b:LATIN SMALL LETTER E WITH CARON
ǐ:0x1d0:LATIN SMALL LETTER I WITH CARON
ǔ:0x1d4:LATIN SMALL LETTER U WITH CARON
ň:0x148:LATIN SMALL LETTER N WITH CARON
ǧ:0x1e7:LATIN SMALL LETTER G WITH CARON
à:0xe0:LATIN SMALL LETTER A WITH GRAVE
ò:0xf2:LATIN SMALL LETTER O WITH GRAVE
è:0xe8:LATIN SMALL LETTER E WITH GRAVE
ì:0xec:LATIN SMALL LETTER I WITH GRAVE
ù:0xf9:LATIN SMALL LETTER U WITH GRAVE
ǹ:0x1f9:LATIN SMALL LETTER N WITH GRAVE
ă:0x103:LATIN SMALL LETTER A WITH BREVE
ŏ:0x14f:LATIN SMALL LETTER O WITH BREVE
ĕ:0x115:LATIN SMALL LETTER E WITH BREVE
ĭ:0x12d:LATIN SMALL LETTER I WITH BREVE
ŭ:0x16d:LATIN SMALL LETTER U WITH BREVE
ğ:0x11f:LATIN SMALL LETTER G WITH BREVE
Ä:0xc4:LATIN CAPITAL LETTER A WITH DIAERESIS
Ö:0xd6:LATIN CAPITAL LETTER O WITH DIAERESIS
Ë:0xcb:LATIN CAPITAL LETTER E WITH DIAERESIS
Ï:0xcf:LATIN CAPITAL LETTER I WITH DIAERESIS
Ü:0xdc:LATIN CAPITAL LETTER U WITH DIAERESIS
Â:0xc2:LATIN CAPITAL LETTER A WITH CIRCUMFLEX
Ô:0xd4:LATIN CAPITAL LETTER O WITH CIRCUMFLEX
Ê:0xca:LATIN CAPITAL LETTER E WITH CIRCUMFLEX
Î:0xce:LATIN CAPITAL LETTER I WITH CIRCUMFLEX
Û:0xdb:LATIN CAPITAL LETTER U WITH CIRCUMFLEX
Ĝ:0x11c:LATIN CAPITAL LETTER G WITH CIRCUMFLEX
Ā:0x100:LATIN CAPITAL LETTER A WITH MACRON
Ō:0x14c:LATIN CAPITAL LETTER O WITH MACRON
Ē:0x112:LATIN CAPITAL LETTER E WITH MACRON
Ī:0x12a:LATIN CAPITAL LETTER I WITH MACRON
Ū:0x16a:LATIN CAPITAL LETTER U WITH MACRON
Ḡ:0x1e20:LATIN CAPITAL LETTER G WITH MACRON
Á:0xc1:LATIN CAPITAL LETTER A WITH ACUTE
Ó:0xd3:LATIN CAPITAL LETTER O WITH ACUTE
É:0xc9:LATIN CAPITAL LETTER E WITH ACUTE
Í:0xcd:LATIN CAPITAL LETTER I WITH ACUTE
Ú:0xda:LATIN CAPITAL LETTER U WITH ACUTE
Ń:0x143:LATIN CAPITAL LETTER N WITH ACUTE
Ḿ:0x1e3e:LATIN CAPITAL LETTER M WITH ACUTE
Ǵ:0x1f4:LATIN CAPITAL LETTER G WITH ACUTE
Ǎ:0x1cd:LATIN CAPITAL LETTER A WITH CARON
Ǒ:0x1d1:LATIN CAPITAL LETTER O WITH CARON
Ě:0x11a:LATIN CAPITAL LETTER E WITH CARON
Ǐ:0x1cf:LATIN CAPITAL LETTER I WITH CARON
Ǔ:0x1d3:LATIN CAPITAL LETTER U WITH CARON
Ň:0x147:LATIN CAPITAL LETTER N WITH CARON
Ǧ:0x1e6:LATIN CAPITAL LETTER G WITH CARON
À:0xc0:LATIN CAPITAL LETTER A WITH GRAVE
Ò:0xd2:LATIN CAPITAL LETTER O WITH GRAVE
È:0xc8:LATIN CAPITAL LETTER E WITH GRAVE
Ì:0xcc:LATIN CAPITAL LETTER I WITH GRAVE
Ù:0xd9:LATIN CAPITAL LETTER U WITH GRAVE
Ǹ:0x1f8:LATIN CAPITAL LETTER N WITH GRAVE
Ă:0x102:LATIN CAPITAL LETTER A WITH BREVE
Ŏ:0x14e:LATIN CAPITAL LETTER O WITH BREVE
Ĕ:0x114:LATIN CAPITAL LETTER E WITH BREVE
Ĭ:0x12c:LATIN CAPITAL LETTER I WITH BREVE
Ŭ:0x16c:LATIN CAPITAL LETTER U WITH BREVE
Ğ:0x11e:LATIN CAPITAL LETTER G WITH BREVE
ǟ:0x1df:LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
ȫ:0x22b:LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
ǖ:0x1d6:LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
ḯ:0x1e2f:LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
ǘ:0x1d8:LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
ǚ:0x1da:LATIN SMALL LETTER U WITH DIAERESIS AND CARON
ǜ:0x1dc:LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
Ǟ:0x1de:LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
Ȫ:0x22a:LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
Ǖ:0x1d5:LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
Ḯ:0x1e2e:LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
Ǘ:0x1d7:LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
Ǚ:0x1d9:LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
Ǜ:0x1db:LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
]]]





[[[
only:AOEIU NMG
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:A
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:O
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:E
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:I
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:U
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:N
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:M
py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:G
===
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:A
ä:0xe4:LATIN SMALL LETTER A WITH DIAERESIS
â:0xe2:LATIN SMALL LETTER A WITH CIRCUMFLEX
ā:0x101:LATIN SMALL LETTER A WITH MACRON
á:0xe1:LATIN SMALL LETTER A WITH ACUTE
ǎ:0x1ce:LATIN SMALL LETTER A WITH CARON
à:0xe0:LATIN SMALL LETTER A WITH GRAVE
ă:0x103:LATIN SMALL LETTER A WITH BREVE
Ä:0xc4:LATIN CAPITAL LETTER A WITH DIAERESIS
Â:0xc2:LATIN CAPITAL LETTER A WITH CIRCUMFLEX
Ā:0x100:LATIN CAPITAL LETTER A WITH MACRON
Á:0xc1:LATIN CAPITAL LETTER A WITH ACUTE
Ǎ:0x1cd:LATIN CAPITAL LETTER A WITH CARON
À:0xc0:LATIN CAPITAL LETTER A WITH GRAVE
Ă:0x102:LATIN CAPITAL LETTER A WITH BREVE
ǟ:0x1df:LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
Ǟ:0x1de:LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:O
ö:0xf6:LATIN SMALL LETTER O WITH DIAERESIS
ô:0xf4:LATIN SMALL LETTER O WITH CIRCUMFLEX
ō:0x14d:LATIN SMALL LETTER O WITH MACRON
ó:0xf3:LATIN SMALL LETTER O WITH ACUTE
ǒ:0x1d2:LATIN SMALL LETTER O WITH CARON
ò:0xf2:LATIN SMALL LETTER O WITH GRAVE
ŏ:0x14f:LATIN SMALL LETTER O WITH BREVE
Ö:0xd6:LATIN CAPITAL LETTER O WITH DIAERESIS
Ô:0xd4:LATIN CAPITAL LETTER O WITH CIRCUMFLEX
Ō:0x14c:LATIN CAPITAL LETTER O WITH MACRON
Ó:0xd3:LATIN CAPITAL LETTER O WITH ACUTE
Ǒ:0x1d1:LATIN CAPITAL LETTER O WITH CARON
Ò:0xd2:LATIN CAPITAL LETTER O WITH GRAVE
Ŏ:0x14e:LATIN CAPITAL LETTER O WITH BREVE
ȫ:0x22b:LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
Ȫ:0x22a:LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:E
ë:0xeb:LATIN SMALL LETTER E WITH DIAERESIS
ê:0xea:LATIN SMALL LETTER E WITH CIRCUMFLEX
ē:0x113:LATIN SMALL LETTER E WITH MACRON
é:0xe9:LATIN SMALL LETTER E WITH ACUTE
ě:0x11b:LATIN SMALL LETTER E WITH CARON
è:0xe8:LATIN SMALL LETTER E WITH GRAVE
ĕ:0x115:LATIN SMALL LETTER E WITH BREVE
Ë:0xcb:LATIN CAPITAL LETTER E WITH DIAERESIS
Ê:0xca:LATIN CAPITAL LETTER E WITH CIRCUMFLEX
Ē:0x112:LATIN CAPITAL LETTER E WITH MACRON
É:0xc9:LATIN CAPITAL LETTER E WITH ACUTE
Ě:0x11a:LATIN CAPITAL LETTER E WITH CARON
È:0xc8:LATIN CAPITAL LETTER E WITH GRAVE
Ĕ:0x114:LATIN CAPITAL LETTER E WITH BREVE
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:I
ï:0xef:LATIN SMALL LETTER I WITH DIAERESIS
î:0xee:LATIN SMALL LETTER I WITH CIRCUMFLEX
ī:0x12b:LATIN SMALL LETTER I WITH MACRON
í:0xed:LATIN SMALL LETTER I WITH ACUTE
ǐ:0x1d0:LATIN SMALL LETTER I WITH CARON
ì:0xec:LATIN SMALL LETTER I WITH GRAVE
ĭ:0x12d:LATIN SMALL LETTER I WITH BREVE
Ï:0xcf:LATIN CAPITAL LETTER I WITH DIAERESIS
Î:0xce:LATIN CAPITAL LETTER I WITH CIRCUMFLEX
Ī:0x12a:LATIN CAPITAL LETTER I WITH MACRON
Í:0xcd:LATIN CAPITAL LETTER I WITH ACUTE
Ǐ:0x1cf:LATIN CAPITAL LETTER I WITH CARON
Ì:0xcc:LATIN CAPITAL LETTER I WITH GRAVE
Ĭ:0x12c:LATIN CAPITAL LETTER I WITH BREVE
ḯ:0x1e2f:LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
Ḯ:0x1e2e:LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:U
ü:0xfc:LATIN SMALL LETTER U WITH DIAERESIS
û:0xfb:LATIN SMALL LETTER U WITH CIRCUMFLEX
ū:0x16b:LATIN SMALL LETTER U WITH MACRON
ú:0xfa:LATIN SMALL LETTER U WITH ACUTE
ǔ:0x1d4:LATIN SMALL LETTER U WITH CARON
ù:0xf9:LATIN SMALL LETTER U WITH GRAVE
ŭ:0x16d:LATIN SMALL LETTER U WITH BREVE
Ü:0xdc:LATIN CAPITAL LETTER U WITH DIAERESIS
Û:0xdb:LATIN CAPITAL LETTER U WITH CIRCUMFLEX
Ū:0x16a:LATIN CAPITAL LETTER U WITH MACRON
Ú:0xda:LATIN CAPITAL LETTER U WITH ACUTE
Ǔ:0x1d3:LATIN CAPITAL LETTER U WITH CARON
Ù:0xd9:LATIN CAPITAL LETTER U WITH GRAVE
Ŭ:0x16c:LATIN CAPITAL LETTER U WITH BREVE
ǖ:0x1d6:LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
ǘ:0x1d8:LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
ǚ:0x1da:LATIN SMALL LETTER U WITH DIAERESIS AND CARON
ǜ:0x1dc:LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
Ǖ:0x1d5:LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
Ǘ:0x1d7:LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
Ǚ:0x1d9:LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
Ǜ:0x1db:LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:N
ń:0x144:LATIN SMALL LETTER N WITH ACUTE
ň:0x148:LATIN SMALL LETTER N WITH CARON
ǹ:0x1f9:LATIN SMALL LETTER N WITH GRAVE
Ń:0x143:LATIN CAPITAL LETTER N WITH ACUTE
Ň:0x147:LATIN CAPITAL LETTER N WITH CARON
Ǹ:0x1f8:LATIN CAPITAL LETTER N WITH GRAVE
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:M
ḿ:0x1e3f:LATIN SMALL LETTER M WITH ACUTE
Ḿ:0x1e3e:LATIN CAPITAL LETTER M WITH ACUTE
.../txt_phone/txt $ py_adhoc_call   nn_ns.CJK.CJK_data.raw.拼音用字   @打印拼音用字囗按名字囗 --full:G
ĝ:0x11d:LATIN SMALL LETTER G WITH CIRCUMFLEX
ḡ:0x1e21:LATIN SMALL LETTER G WITH MACRON
ǵ:0x1f5:LATIN SMALL LETTER G WITH ACUTE
ǧ:0x1e7:LATIN SMALL LETTER G WITH CARON
ğ:0x11f:LATIN SMALL LETTER G WITH BREVE
Ĝ:0x11c:LATIN CAPITAL LETTER G WITH CIRCUMFLEX
Ḡ:0x1e20:LATIN CAPITAL LETTER G WITH MACRON
Ǵ:0x1f4:LATIN CAPITAL LETTER G WITH ACUTE
Ǧ:0x1e6:LATIN CAPITAL LETTER G WITH CARON
Ğ:0x11e:LATIN CAPITAL LETTER G WITH BREVE
]]]





#]]]'''
__all__ = r'''
拼音用字囗带音调字母

打印拼音用字囗按名字囗
    找出拼音用字囗按名字囗
        拼音用字囗带音调字母
'''.split()#'''
__all__

import unicodedata
#print(dir(unicodedata))
#   .name
#   .lookup


def 找出拼音用字囗按名字囗(*, full):
    if type(full) is str:
        azs = full.upper()
    elif full:
        rng4AZ = range(ord('A'), 1+ord('Z'))
        azs = ''.join(map(chr, rng4AZ))
    else:
        azs = 'AOEIUNMG'
    dcs = 'DIAERESIS CIRCUMFLEX MACRON ACUTE CARON GRAVE BREVE'.split()
    uls = 'SMALL CAPITAL'.split()
    fmt0 = 'LATIN {ul} LETTER {az} WITH {dc}'
    fmt1 = 'LATIN {ul} LETTER {az} WITH DIAERESIS AND {dc}'
    fmts = [fmt0, fmt1]
    for fmt in fmts:
     for ul in uls:
      for dc in dcs:
       for az in azs:
        nm = fmt.format(ul=ul, dc=dc, az=az)
        try:
            ch = unicodedata.lookup(nm)
        except LookupError:
            ch = None

        if ch is None:
            continue
            ch = '-'
            hx = '-'
        else:
            hx = hex(ord(ch))


        #print(f'{ch}:{hx}:{nm}')
        yield ch, hx, nm
def 打印拼音用字囗按名字囗(*, full):
    for ch, hx, nm in 找出拼音用字囗按名字囗(full=full):
        print(f'{ch}:{hx}:{nm}')


拼音用字囗带音调字母='=aāáǎà=AĀÁǍÀ=oōóǒò=OŌÓǑÒ=eēéěè=EĒÉĚÈ=iīíǐì=IĪÍǏÌ=uūúǔù=UŪÚǓÙ=üǖǘǚǜ=ÜǕǗǙǛ=nńňǹ=NŃŇǸ=mḿ=MḾ=gḡǵǧ=GḠǴǦ='

from nn_ns.CJK.CJK_data.raw.拼音用字 import 打印拼音用字囗按名字囗, 找出拼音用字囗按名字囗, 拼音用字囗带音调字母
from nn_ns.CJK.CJK_data.raw.拼音用字 import *

