r'''
RepositorySetting

======


    , RepositorySetting__using_dir_cmp__ignorefile__using_file_cmp__file_patch_ver1__using_IFileSystem4update__fsys_delta_is_fsys_update_cmd
    , RepositorySetting__using_dir_cmp__ignorefile__using_file_cmp__file_patch_ver1__using_IFileSystem4update__fsys_delta_is_branch_history_cmd
#'''





__all__ = '''
    RepositorySetting__using_dir_cmp__ignorefile__using_file_cmp__file_patch_ver1__using_IFileSystem4update__fsys_delta_is_fsys_update_cmd
    RepositorySetting__using_dir_cmp__ignorefile__using_file_cmp__file_patch_ver1__using_IFileSystem4update__fsys_delta_is_branch_history_cmd
    '''.split()


___begin_mark_of_excluded_global_names__0___ = ...

from nn_ns.filedir.backup_tools.IRepositorySetting import IRepositorySetting__init_constants__branches_together__cache_min_len_inf_dir__init_caches, IRepositorySetting__default_move_cmd_line_fmt
from nn_ns.filedir.backup_tools.IRepositorySetting__working_root_dir_path__using_dir_cmp__ignorefile import IRepositorySetting__working_root_dir_path__using_dir_cmp__ignorefile


from nn_ns.filedir.backup_tools.IRepositorySetting__using_file_cmp__file_patch import IRepositorySetting__using_file_cmp__file_patch_ver1

from nn_ns.filedir.backup_tools.IRepositorySetting__using_IFileSystem4update__fsys_delta import IRepositorySetting__using_IFileSystem4update__fsys_delta_is_fsys_update_cmd, IRepositorySetting__using_IFileSystem4update__fsys_delta_is_branch_history_cmd

___end_mark_of_excluded_global_names__0___ = ...



_common_bases = (IRepositorySetting__using_file_cmp__file_patch_ver1, IRepositorySetting__working_root_dir_path__using_dir_cmp__ignorefile, IRepositorySetting__default_move_cmd_line_fmt, IRepositorySetting__init_constants__branches_together__cache_min_len_inf_dir__init_caches)
class RepositorySetting__using_dir_cmp__ignorefile__using_file_cmp__file_patch_ver1__using_IFileSystem4update__fsys_delta_is_fsys_update_cmd(IRepositorySetting__using_IFileSystem4update__fsys_delta_is_fsys_update_cmd, *_common_bases): pass
class RepositorySetting__using_dir_cmp__ignorefile__using_file_cmp__file_patch_ver1__using_IFileSystem4update__fsys_delta_is_branch_history_cmd(IRepositorySetting__using_IFileSystem4update__fsys_delta_is_branch_history_cmd, *_common_bases): pass



